language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
services:
- docker
dist: trusty
before_install:
  - "pip install --upgrade setuptools"
  - "pip install --upgrade pip"
  - "pip install -e .[tests]"
install: "pip install -r requirements.txt"
script:
  - python3 -m flake8
  - find . -iname "*.py" | xargs pylint --rcfile .pylintrc
  - python3 -m pytest ./tests/test_*.py --cov buku -vv
before_deploy:
- sudo apt-get update -qy
- sudo apt-get install -qy python3 python3-pip
- python3 -m pip install packagecore
- packagecore -o dist/ "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api_key:
    secure: OAl+QyuYONo8X18iEqPZCYzAI59eacz6y0AG0Oc5JAZlnMI1u0WCb1VH+jTTMax+tux80YCGN2mX/KcHbEflarTD03bkoOQ4UpIeWhJ9vTvu9VmzobvZY84PK0eSeEqHuiwrQbKO+bxwwNe2AMYGQMsqJGCN8d7UV2+ilm3SgRg0Nf8gJ9an+M/cOeBtdy87M9ugjnKnzqSJY3Qu9ffx+GsptxMWlFP143CB4WWLaBGp3F+SRoWQaPkO3u+9HrRZVl1yONVQ0F8ax2SWBVQWFr2to0fdftvL1UXRdynOMP0Foi2lrhaR+6fre9n2zsllJdapMEkkzkWdsjomikIQZnARTxznlV8xuTWsXXsRFhFJt/YM5VKFvmWNY+OSSKM63dCG5m2WU6ZLQ8ZhsEHKZDr9GPCaq4PwtVfh4Qn/xELx+sIIAwHLFybk4F/EZdjm1gWDu/COXlbLIv2TQhF0o99hu8Oxt7/Xyi/a0hFE3myeNJh+BizjlmBHC6dd7CKpW77ZKLtnxD/CSSMw2p4L9BfdnIfIChVi7lY0HMocE4qXEkeu8+4h2dsOOc22w9wwQ69R5s10QtpNRo47N+O06ZQyzgy6xtBPXiAODiRUHKZECPKwd/rsa4OGIG7C83H2zSGPUPHJGmYgytUMYPpkWpo1Fr42J8m0RPlV88D+Ua8=
  file_glob: true
  file:
      - dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: shaggytwodope/testbuku
    python: "3.6"